<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="桂宝元" ignored="0" name="mytest" tests="4" failures="1" timestamp="05 九月 2018 03:47:42 GMT" time="0.521" errors="0">
  <testcase name="f" time="0.017" classname="other.testngtest.NewTest">
    <skipped/>
  </testcase> <!-- f -->
  <testcase name="f" time="0.002" classname="other.testngtest.NewTest">
    <skipped/>
  </testcase> <!-- f -->
  <testcase name="f" time="0.002" classname="other.testngtest.NewTest">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at other.testngtest.NewTest.f(NewTest.java:8)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="g" time="0.0" classname="other.testngtest.NewTest">
    <skipped/>
  </testcase> <!-- g -->
</testsuite> <!-- mytest -->
