<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="桂宝元" name="mytest2" tests="4" failures="1" timestamp="13 Aug 2018 04:24:58 GMT" time="0.077" errors="0">
  <testcase name="a" time="0.016" classname="test.testng.parralel.MethodP">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
	at test.testng.parralel.MethodP.a(MethodP.java:18)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- a -->
  <testcase name="f" time="0.003" classname="test.testng.parralel.MethodP"/>
  <testcase name="f" time="0.001" classname="test.testng.parralel.MethodP"/>
  <testcase name="f" time="0.005" classname="test.testng.parralel.NewTest"/>
</testsuite> <!-- mytest2 -->
