<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
    <line>
      <![CDATA[[debug] deviceName: GiONEE_GN5001S]]>
    </line>
    <line>
      <![CDATA[[debug] 执行命令：[cmd, /c, adb connect 192.168.20.138:5555]]]>
    </line>
    <line>
      <![CDATA[[debug] 命令结果：already connected to 192.168.20.138:5555]]>
    </line>
    <line>
      <![CDATA[[debug] 执行命令：[cmd, /c, appium -a 127.0.0.1 -p 4996 -U 192.168.20.138:5555 -bp 4997]]]>
    </line>
    <line>
      <![CDATA[[debug] [35m[Appium][39m Welcome to Appium v1.8.1]]>
    </line>
    <line>
      <![CDATA[[debug] [35m[Appium][39m Non-default server args:]]>
    </line>
    <line>
      <![CDATA[[debug] [35m[Appium][39m   address: 127.0.0.1]]>
    </line>
    <line>
      <![CDATA[[debug] [35m[Appium][39m   port: 4996]]>
    </line>
    <line>
      <![CDATA[[debug] [35m[Appium][39m   bootstrapPort: 4997]]>
    </line>
    <line>
      <![CDATA[[debug] [35m[Appium][39m   udid: 192.168.20.138:5555]]>
    </line>
    <line>
      <![CDATA[[debug] [35m[Appium][39m Deprecated server args:]]>
    </line>
    <line>
      <![CDATA[[debug] [35m[Appium][39m   [31m-U,--udid[39m => --default-capabilities '{"udid":"192.168.20.138:5555"}']]>
    </line>
    <line>
      <![CDATA[[debug] [35m[Appium][39m Default capabilities, which will be added to each request unless overridden by desired capabilities:]]>
    </line>
    <line>
      <![CDATA[[debug] [35m[Appium][39m   udid: 192.168.20.138:5555]]>
    </line>
    <line>
      <![CDATA[[debug] [35m[HTTP][39m Could not start REST http interface listener. The requested port may already be in use. Please make sure there is no other instance of this server running already.]]>
    </line>
    <line>
      <![CDATA[[error] appiumServer无法启动，可能是已存在]]>
    </line>
    <line>
      <![CDATA[[debug] Fatal Error: listen EADDRINUSE 127.0.0.1:4996]]>
    </line>
    <line>
      <![CDATA[[debug]     at Object._errnoException (util.js:992:11)]]>
    </line>
    <line>
      <![CDATA[[debug]     at _exceptionWithHostPort (util.js:1014:20)]]>
    </line>
    <line>
      <![CDATA[[debug]     at Server.setupListenHandle [as _listen2] (net.js:1355:14)]]>
    </line>
    <line>
      <![CDATA[[debug]     at listenInCluster (net.js:1396:12)]]>
    </line>
    <line>
      <![CDATA[[debug]     at doListen (net.js:1505:7)]]>
    </line>
    <line>
      <![CDATA[[debug]     at _combinedTickCallback (internal/process/next_tick.js:141:11)]]>
    </line>
    <line>
      <![CDATA[[debug]     at process._tickCallback (internal/process/next_tick.js:180:9)]]>
    </line>
    <line>
      <![CDATA[[error] 初始化driver失败]]>
    </line>
    <line>
      <![CDATA[[debug] 执行命令：[cmd, /c, taskkill /F /PID 12044]]]>
    </line>
    <line>
      <![CDATA[[debug] 命令结果：����: û���ҵ����� "12044"��]]>
    </line>
    <line>
      <![CDATA[[debug] 12044]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="4539" started-at="2018-08-10T12:07:13Z" finished-at="2018-08-10T12:07:17Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="4539" started-at="2018-08-10T12:07:13Z" finished-at="2018-08-10T12:07:17Z">
      <class name="gby.testng.testcase.InitDriverCase">
        <test-method status="FAIL" signature="f(java.lang.String)[pri:0, instance:gby.testng.testcase.InitDriverCase@4883b407]" name="f" duration-ms="4271" started-at="2018-08-10T20:07:13Z" finished-at="2018-08-10T20:07:17Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[GiONEE_GN5001S]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NoSuchMethodError">
            <full-stacktrace>
              <![CDATA[java.lang.NoSuchMethodError
	at java.lang.Thread.destroy(Unknown Source)
	at gby.testng.testcase.InitDriverCase.f(InitDriverCase.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NoSuchMethodError -->
          <reporter-output>
            <line>
              <![CDATA[[debug] deviceName: GiONEE_GN5001S]]>
            </line>
            <line>
              <![CDATA[[debug] 执行命令：[cmd, /c, adb connect 192.168.20.138:5555]]]>
            </line>
            <line>
              <![CDATA[[debug] 命令结果：already connected to 192.168.20.138:5555]]>
            </line>
            <line>
              <![CDATA[[debug] 执行命令：[cmd, /c, appium -a 127.0.0.1 -p 4996 -U 192.168.20.138:5555 -bp 4997]]]>
            </line>
            <line>
              <![CDATA[[debug] [35m[Appium][39m Welcome to Appium v1.8.1]]>
            </line>
            <line>
              <![CDATA[[debug] [35m[Appium][39m Non-default server args:]]>
            </line>
            <line>
              <![CDATA[[debug] [35m[Appium][39m   address: 127.0.0.1]]>
            </line>
            <line>
              <![CDATA[[debug] [35m[Appium][39m   port: 4996]]>
            </line>
            <line>
              <![CDATA[[debug] [35m[Appium][39m   bootstrapPort: 4997]]>
            </line>
            <line>
              <![CDATA[[debug] [35m[Appium][39m   udid: 192.168.20.138:5555]]>
            </line>
            <line>
              <![CDATA[[debug] [35m[Appium][39m Deprecated server args:]]>
            </line>
            <line>
              <![CDATA[[debug] [35m[Appium][39m   [31m-U,--udid[39m => --default-capabilities '{"udid":"192.168.20.138:5555"}']]>
            </line>
            <line>
              <![CDATA[[debug] [35m[Appium][39m Default capabilities, which will be added to each request unless overridden by desired capabilities:]]>
            </line>
            <line>
              <![CDATA[[debug] [35m[Appium][39m   udid: 192.168.20.138:5555]]>
            </line>
            <line>
              <![CDATA[[debug] [35m[HTTP][39m Could not start REST http interface listener. The requested port may already be in use. Please make sure there is no other instance of this server running already.]]>
            </line>
            <line>
              <![CDATA[[error] appiumServer无法启动，可能是已存在]]>
            </line>
            <line>
              <![CDATA[[debug] Fatal Error: listen EADDRINUSE 127.0.0.1:4996]]>
            </line>
            <line>
              <![CDATA[[debug]     at Object._errnoException (util.js:992:11)]]>
            </line>
            <line>
              <![CDATA[[debug]     at _exceptionWithHostPort (util.js:1014:20)]]>
            </line>
            <line>
              <![CDATA[[debug]     at Server.setupListenHandle [as _listen2] (net.js:1355:14)]]>
            </line>
            <line>
              <![CDATA[[debug]     at listenInCluster (net.js:1396:12)]]>
            </line>
            <line>
              <![CDATA[[debug]     at doListen (net.js:1505:7)]]>
            </line>
            <line>
              <![CDATA[[debug]     at _combinedTickCallback (internal/process/next_tick.js:141:11)]]>
            </line>
            <line>
              <![CDATA[[debug]     at process._tickCallback (internal/process/next_tick.js:180:9)]]>
            </line>
            <line>
              <![CDATA[[error] 初始化driver失败]]>
            </line>
          </reporter-output>
        </test-method> <!-- f -->
        <test-method status="PASS" signature="setDown()[pri:0, instance:gby.testng.testcase.InitDriverCase@4883b407]" name="setDown" duration-ms="247" started-at="2018-08-10T20:07:17Z" finished-at="2018-08-10T20:07:17Z">
          <reporter-output>
            <line>
              <![CDATA[[debug] 执行命令：[cmd, /c, taskkill /F /PID 12044]]]>
            </line>
            <line>
              <![CDATA[[debug] 命令结果：����: û���ҵ����� "12044"��]]>
            </line>
            <line>
              <![CDATA[[debug] 12044]]>
            </line>
          </reporter-output>
        </test-method> <!-- setDown -->
      </class> <!-- gby.testng.testcase.InitDriverCase -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
