<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="桂宝元" name="gby.testng.testcase.PublishPostCase" tests="3" failures="2" timestamp="07 九月 2018 05:53:37 GMT" time="36.686" errors="0">
  <testcase name="intoPublisPostPage" time="21.081" classname="gby.testng.testcase.PublishPostCase">
    <failure type="java.lang.AssertionError" message="【loginButton】元素识别失败，该测试方法自动结束失败">
      <![CDATA[java.lang.AssertionError: 【loginButton】元素识别失败，该测试方法自动结束失败
at org.testng.Assert.fail(Assert.java:96)
at gby.appium.page.BasePage.findElement(BasePage.java:94)
at gby.appium.page.LoginPage.login(LoginPage.java:15)
at gby.appium.page.FindRoommateBasePage.openPublishPage(FindRoommateBasePage.java:43)
at gby.testng.testcase.PublishPostCase.intoPublisPostPage(PublishPostCase.java:39)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- intoPublisPostPage -->
  <testcase name="publishRoom" time="0.000" classname="gby.testng.testcase.PublishPostCase">
    <skipped/>
  </testcase> <!-- publishRoom -->
  <testcase name="deletePost" time="15.605" classname="gby.testng.testcase.PublishPostCase">
    <failure type="java.lang.AssertionError" message="【myPostButton】元素识别失败，该测试方法自动结束失败">
      <![CDATA[java.lang.AssertionError: 【myPostButton】元素识别失败，该测试方法自动结束失败
at org.testng.Assert.fail(Assert.java:96)
at gby.appium.page.BasePage.findElement(BasePage.java:94)
at gby.appium.page.MinePage.deletePost(MinePage.java:32)
at gby.testng.testcase.PublishPostCase.deletePost(PublishPostCase.java:64)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:214)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- deletePost -->
</testsuite> <!-- gby.testng.testcase.PublishPostCase -->
